// Code generated for YaroslavalsoraY services
// © YaroslavalsoraY 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "inventory/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

type InventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryRepository) EXPECT() *InventoryRepository_Expecter {
	return &InventoryRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, uuid
func (_m *InventoryRepository) GetPart(ctx context.Context, uuid string) (model.PartInfo, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 model.PartInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PartInfo, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PartInfo); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.PartInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryRepository_Expecter) GetPart(ctx interface{}, uuid interface{}) *InventoryRepository_GetPart_Call {
	return &InventoryRepository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uuid)}
}

func (_c *InventoryRepository_GetPart_Call) Run(run func(ctx context.Context, uuid string)) *InventoryRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryRepository_GetPart_Call) Return(_a0 model.PartInfo, _a1 error) *InventoryRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_GetPart_Call) RunAndReturn(run func(context.Context, string) (model.PartInfo, error)) *InventoryRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filetrs
func (_m *InventoryRepository) ListParts(ctx context.Context, filetrs model.Filters) ([]model.PartInfo, error) {
	ret := _m.Called(ctx, filetrs)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.PartInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Filters) ([]model.PartInfo, error)); ok {
		return rf(ctx, filetrs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Filters) []model.PartInfo); ok {
		r0 = rf(ctx, filetrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PartInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Filters) error); ok {
		r1 = rf(ctx, filetrs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filetrs model.Filters
func (_e *InventoryRepository_Expecter) ListParts(ctx interface{}, filetrs interface{}) *InventoryRepository_ListParts_Call {
	return &InventoryRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filetrs)}
}

func (_c *InventoryRepository_ListParts_Call) Run(run func(ctx context.Context, filetrs model.Filters)) *InventoryRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Filters))
	})
	return _c
}

func (_c *InventoryRepository_ListParts_Call) Return(_a0 []model.PartInfo, _a1 error) *InventoryRepository_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_ListParts_Call) RunAndReturn(run func(context.Context, model.Filters) ([]model.PartInfo, error)) *InventoryRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
