with-expecter: true
boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  inventory/internal/service:
    config:
      include-regex: ".*Service"
  inventory/internal/repository:
    config:
      include-regex: ".*Repository"
  
  order/internal/service:
    config:
      include-regex: ".*Service"
  order/internal/repository:
    config:
      include-regex: ".*Repository"
  order/internal/client/grpc:
    config:
      include-regex: ".*Client"

  payment/internal/service:
    config:
      include-regex: ".*Service"
  
