// Code generated for YaroslavalsoraY services
// © YaroslavalsoraY 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// KafkaConsumerConfig is an autogenerated mock type for the KafkaConsumerConfig type
type KafkaConsumerConfig struct {
	mock.Mock
}

type KafkaConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *KafkaConsumerConfig) EXPECT() *KafkaConsumerConfig_Expecter {
	return &KafkaConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *KafkaConsumerConfig) Config() *sarama.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if rf, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}

	return r0
}

// KafkaConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type KafkaConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *KafkaConsumerConfig_Expecter) Config() *KafkaConsumerConfig_Config_Call {
	return &KafkaConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *KafkaConsumerConfig_Config_Call) Run(run func()) *KafkaConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KafkaConsumerConfig_Config_Call) Return(_a0 *sarama.Config) *KafkaConsumerConfig_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KafkaConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *KafkaConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function with no fields
func (_m *KafkaConsumerConfig) GroupID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// KafkaConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type KafkaConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *KafkaConsumerConfig_Expecter) GroupID() *KafkaConsumerConfig_GroupID_Call {
	return &KafkaConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *KafkaConsumerConfig_GroupID_Call) Run(run func()) *KafkaConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KafkaConsumerConfig_GroupID_Call) Return(_a0 string) *KafkaConsumerConfig_GroupID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KafkaConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *KafkaConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// TopicName provides a mock function with no fields
func (_m *KafkaConsumerConfig) TopicName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopicName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// KafkaConsumerConfig_TopicName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopicName'
type KafkaConsumerConfig_TopicName_Call struct {
	*mock.Call
}

// TopicName is a helper method to define mock.On call
func (_e *KafkaConsumerConfig_Expecter) TopicName() *KafkaConsumerConfig_TopicName_Call {
	return &KafkaConsumerConfig_TopicName_Call{Call: _e.mock.On("TopicName")}
}

func (_c *KafkaConsumerConfig_TopicName_Call) Run(run func()) *KafkaConsumerConfig_TopicName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KafkaConsumerConfig_TopicName_Call) Return(_a0 string) *KafkaConsumerConfig_TopicName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KafkaConsumerConfig_TopicName_Call) RunAndReturn(run func() string) *KafkaConsumerConfig_TopicName_Call {
	_c.Call.Return(run)
	return _c
}

// NewKafkaConsumerConfig creates a new instance of KafkaConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaConsumerConfig {
	mock := &KafkaConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
