// Code generated for YaroslavalsoraY services
// © YaroslavalsoraY 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// OrderHttpConfig is an autogenerated mock type for the OrderHttpConfig type
type OrderHttpConfig struct {
	mock.Mock
}

type OrderHttpConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderHttpConfig) EXPECT() *OrderHttpConfig_Expecter {
	return &OrderHttpConfig_Expecter{mock: &_m.Mock}
}

// HeaderTimeout provides a mock function with no fields
func (_m *OrderHttpConfig) HeaderTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HeaderTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// OrderHttpConfig_HeaderTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderTimeout'
type OrderHttpConfig_HeaderTimeout_Call struct {
	*mock.Call
}

// HeaderTimeout is a helper method to define mock.On call
func (_e *OrderHttpConfig_Expecter) HeaderTimeout() *OrderHttpConfig_HeaderTimeout_Call {
	return &OrderHttpConfig_HeaderTimeout_Call{Call: _e.mock.On("HeaderTimeout")}
}

func (_c *OrderHttpConfig_HeaderTimeout_Call) Run(run func()) *OrderHttpConfig_HeaderTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHttpConfig_HeaderTimeout_Call) Return(_a0 time.Duration) *OrderHttpConfig_HeaderTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHttpConfig_HeaderTimeout_Call) RunAndReturn(run func() time.Duration) *OrderHttpConfig_HeaderTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// HttpAdress provides a mock function with no fields
func (_m *OrderHttpConfig) HttpAdress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HttpAdress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderHttpConfig_HttpAdress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HttpAdress'
type OrderHttpConfig_HttpAdress_Call struct {
	*mock.Call
}

// HttpAdress is a helper method to define mock.On call
func (_e *OrderHttpConfig_Expecter) HttpAdress() *OrderHttpConfig_HttpAdress_Call {
	return &OrderHttpConfig_HttpAdress_Call{Call: _e.mock.On("HttpAdress")}
}

func (_c *OrderHttpConfig_HttpAdress_Call) Run(run func()) *OrderHttpConfig_HttpAdress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHttpConfig_HttpAdress_Call) Return(_a0 string) *OrderHttpConfig_HttpAdress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHttpConfig_HttpAdress_Call) RunAndReturn(run func() string) *OrderHttpConfig_HttpAdress_Call {
	_c.Call.Return(run)
	return _c
}

// ShutdownTimeout provides a mock function with no fields
func (_m *OrderHttpConfig) ShutdownTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShutdownTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// OrderHttpConfig_ShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShutdownTimeout'
type OrderHttpConfig_ShutdownTimeout_Call struct {
	*mock.Call
}

// ShutdownTimeout is a helper method to define mock.On call
func (_e *OrderHttpConfig_Expecter) ShutdownTimeout() *OrderHttpConfig_ShutdownTimeout_Call {
	return &OrderHttpConfig_ShutdownTimeout_Call{Call: _e.mock.On("ShutdownTimeout")}
}

func (_c *OrderHttpConfig_ShutdownTimeout_Call) Run(run func()) *OrderHttpConfig_ShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderHttpConfig_ShutdownTimeout_Call) Return(_a0 time.Duration) *OrderHttpConfig_ShutdownTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderHttpConfig_ShutdownTimeout_Call) RunAndReturn(run func() time.Duration) *OrderHttpConfig_ShutdownTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderHttpConfig creates a new instance of OrderHttpConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderHttpConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderHttpConfig {
	mock := &OrderHttpConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
