// Code generated for YaroslavalsoraY services
// © YaroslavalsoraY 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// KafkaProducerConfig is an autogenerated mock type for the KafkaProducerConfig type
type KafkaProducerConfig struct {
	mock.Mock
}

type KafkaProducerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *KafkaProducerConfig) EXPECT() *KafkaProducerConfig_Expecter {
	return &KafkaProducerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *KafkaProducerConfig) Config() *sarama.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if rf, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}

	return r0
}

// KafkaProducerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type KafkaProducerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *KafkaProducerConfig_Expecter) Config() *KafkaProducerConfig_Config_Call {
	return &KafkaProducerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *KafkaProducerConfig_Config_Call) Run(run func()) *KafkaProducerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KafkaProducerConfig_Config_Call) Return(_a0 *sarama.Config) *KafkaProducerConfig_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KafkaProducerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *KafkaProducerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// TopicName provides a mock function with no fields
func (_m *KafkaProducerConfig) TopicName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopicName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// KafkaProducerConfig_TopicName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopicName'
type KafkaProducerConfig_TopicName_Call struct {
	*mock.Call
}

// TopicName is a helper method to define mock.On call
func (_e *KafkaProducerConfig_Expecter) TopicName() *KafkaProducerConfig_TopicName_Call {
	return &KafkaProducerConfig_TopicName_Call{Call: _e.mock.On("TopicName")}
}

func (_c *KafkaProducerConfig_TopicName_Call) Run(run func()) *KafkaProducerConfig_TopicName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KafkaProducerConfig_TopicName_Call) Return(_a0 string) *KafkaProducerConfig_TopicName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KafkaProducerConfig_TopicName_Call) RunAndReturn(run func() string) *KafkaProducerConfig_TopicName_Call {
	_c.Call.Return(run)
	return _c
}

// NewKafkaProducerConfig creates a new instance of KafkaProducerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaProducerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaProducerConfig {
	mock := &KafkaProducerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
