// Code generated for YaroslavalsoraY services
// © YaroslavalsoraY 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InventoryGRPCConfig is an autogenerated mock type for the InventoryGRPCConfig type
type InventoryGRPCConfig struct {
	mock.Mock
}

type InventoryGRPCConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryGRPCConfig) EXPECT() *InventoryGRPCConfig_Expecter {
	return &InventoryGRPCConfig_Expecter{mock: &_m.Mock}
}

// InventoryAdress provides a mock function with no fields
func (_m *InventoryGRPCConfig) InventoryAdress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InventoryAdress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// InventoryGRPCConfig_InventoryAdress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InventoryAdress'
type InventoryGRPCConfig_InventoryAdress_Call struct {
	*mock.Call
}

// InventoryAdress is a helper method to define mock.On call
func (_e *InventoryGRPCConfig_Expecter) InventoryAdress() *InventoryGRPCConfig_InventoryAdress_Call {
	return &InventoryGRPCConfig_InventoryAdress_Call{Call: _e.mock.On("InventoryAdress")}
}

func (_c *InventoryGRPCConfig_InventoryAdress_Call) Run(run func()) *InventoryGRPCConfig_InventoryAdress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InventoryGRPCConfig_InventoryAdress_Call) Return(_a0 string) *InventoryGRPCConfig_InventoryAdress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryGRPCConfig_InventoryAdress_Call) RunAndReturn(run func() string) *InventoryGRPCConfig_InventoryAdress_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryGRPCConfig creates a new instance of InventoryGRPCConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryGRPCConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryGRPCConfig {
	mock := &InventoryGRPCConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
