// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderRes interface {
	cancelOrderRes()
}

type CreateNewOrderRes interface {
	createNewOrderRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type PayOrderRes interface {
	payOrderRes()
}
